### ISSUE TITLE
`no_override` option doesn't work and naming is confusing

### ISSUE THREAD

**Issue by Vadorequest** [bobheadxi/deployments#25]
Using
```yml
      # Create a GitHub deployment (within a GitHub environment), useful to keep a public track of all deployments directly in GitHub
      - name: Start GitHub deployment
        uses: bobheadxi/deployments@v0.4.3 # See https://github.com/bobheadxi/deployments
        id: start-github-deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: storybook # Uses "storybook" as GitHub environment name, because we don't need to manage multiple environments for storybook
          no_override: false # Disables auto marking previous environments as "inactive", as they're still active (Vercel deployments don't auto-deactivate) and it would remove the previous deployment links needlessly

```

It yields (see https://github.com/UnlyEd/next-right-now/runs/1756790711?check_suite_focus=true):

```
Warning: Unexpected input(s) 'no_override', valid inputs are ['token', 'step', 'auto_inactive', 'logs', 'desc', 'ref', 'env', 'transient', 'deployment_id', 'env_url', 'status']
##[debug]Loading env
Run bobheadxi/deployments@v0.4.3
  with:
    step: start
    token: ***
    env: customer1-production
    no_override: false
  env:
    MANUAL_TRIGGER_CUSTOMER: 
    CUSTOMER_REF_TO_DEPLOY: customer1
initializing deployment  for customer1-production @ refs/heads/v2-mst-aptd-gcms-lcz-sty
found 2 existing deployments for env customer1-production - marking as inactive
setting deployment 'customer1-production.315946607' (c826034a4cb1152be631e309131d60865c34605a) state to "inactive"
setting deployment 'customer1-production.315943090' (afc2096b00102f18274315633f2394c4bfd5fa30) state to "inactive"
2 deployments updated
created deployment 315946665 for customer1-production @ refs/heads/v2-mst-aptd-gcms-lcz-sty
::set-output name=deployment_id::315946665
##[debug]steps.start-github-deployment.outputs.deployment_id='315946665'
::set-output name=env::customer1-production
##[debug]steps.start-github-deployment.outputs.env='customer1-production'
deployment status set to "in_progress"
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Start GitHub deployment
```

> Warning: Unexpected input(s) 'no_override', valid inputs are ['token', 'step', 'auto_inactive', 'logs', 'desc', 'ref', 'env', 'transient', 'deployment_id', 'env_url', 'status']
>
> found 2 existing deployments for env customer1-production - marking as inactive

The `no_override` option isn't recognized and probably ignored. Thus, specifying it doesn't change anything and it doesn't do what it should.

Also, the naming is highly confusing, and makes the code hard to understand.

https://github.com/bobheadxi/deployments/blob/f8bee07b229963d07fb99cdd2dcb04515a3848ad/src/main.ts#L23-L33

It should be renamed as something like `auto_deactivate`, something of the sort.

I'm still confused at whether you meant it to automatically deactivate old deployments, by reading the code I'd say it doesn't auto-deactivate by default, but it does.

**Comment by bobheadxi** [comment]
Some history on `no_override`, its behaviour was changed here: https://github.com/bobheadxi/deployments/pull/10

Just for my own sanity, a quick rundown of what it does now, since as you can see from that PR I was already confused then:

* If `no_override` is _not_ explicitly set to false, `noOverride` is true, in which case we _do not_ deactivate
* If `no_override` _is_ explicitly set to false, `noOverride` is false, in which case `!noOverride` => we _do_ deactivate (the case you got)

I agree this is might be poorly named and might not be great behaviour, and `auto_deactivate` sounds like a great name for this instead. Regardless, [my docs claim that `no_override` defaults to true](https://github.com/bobheadxi/deployments#step-start), which indeed _should_ be the case as per the above.

> I'm still confused at whether you meant it to automatically deactivate old deployments, by reading the code I'd say it doesn't auto-deactivate by default, but it does.

Do you have a link to build logs that indicates it does? I'm looking at the commit where you removed your `no_override` setting, e.g. https://github.com/UnlyEd/next-right-now/runs/1756890721 and nothing seems to indicate old deployments getting removed

**Comment by Vadorequest** [comment]
Maybe my understanding of the "deactivation" is wrong then, because looking at https://github.com/UnlyEd/next-right-now/deployments/activity_log?environment=customer1-staging I don't understand why there is only one "Active" with a "View deployment" link, there should be several of them.

My first understanding of the `no_override` was it wouldn't deactivate old deployments, but each new deployment was triggering the old ones to become "inactive", that's why I tried to set it to false (in case it'd behave to the contrary of my beliefs) but the behaviour did not change. (or, I didn't figure out what changed)

**Comment by bobheadxi** [comment]
When I made this, the "override" behaviour referred to "this current deployment, will _override_ all older deployments, but setting them to deactivated.

The setting is called `no_override` because I imagined that _wanting_ old deployments to be deactivated would be the default preference - namely, it seemed common practice for a new deployment to "override" older ones - and my personal preference is to default to a "falsy" value. In this case, to _disable_ the "override" behaviour:

```false
no_override: true
```

aka "do not override"

**Comment by Vadorequest** [comment]
> wanting old deployments to be deactivated would be the default preference

Agreed, for most use cases, but mine is different since the deployments aren't really deactivated (they're deployed on Vercel) and I see no point deactivating it them in GitHub while they're still active on Vercel. (especially as it removes the deployment link, which might be really useful)

I'll try again, but it's odd deployments were deactivated for me, when I wasn't specifying the `no_override` (I was relying on the default value at the beginning)

**Comment by bobheadxi** [comment]
You should set `no_override: true` to disable the deactivation, let me know if that doesn't work!

**Comment by Vadorequest** [comment]
I thought that was the default. 🤔 
![image](https://user-images.githubusercontent.com/3807458/105635971-2972da00-5e66-11eb-9f13-9a504d899cf0.png)

**Comment by Vadorequest** [comment]
Using `true` didn't change anything, my previous deployments became inactive again.
https://github.com/UnlyEd/next-right-now/deployments

![image](https://user-images.githubusercontent.com/3807458/105636285-00ebdf80-5e68-11eb-8769-15900960e04b.png)

**Comment by bobheadxi** [comment]
I just cut a new release: https://github.com/bobheadxi/deployments/releases/tag/v0.5.0

This also adds `log_args: true` to help you validate what `deployments` is using!

**Comment by zacklitzsinger** [comment]
I had to set `auto_inactive: false` to get this to work. I set it on the start and finish steps.

Also, it looks like `log_args` is missing from the [action yaml file](https://github.com/bobheadxi/deployments/blob/master/action.yml).

**Comment by BBaoVanC** [comment]
Not sure if this is the right place to put it but how can I make it so the previous deploys on the same pull request are marked as inactive, but not the deploys of other pull requests. I want it so each pull request has its own single single active deploy, since the URLs I'm deploying to have that number in them.

**Comment by bobheadxi** [comment]
`no_override` is now `override`, and definitely works as of [`bobheadxi/deployments@v1`](https://github.com/bobheadxi/deployments/discussions/82)!

> how can I make it so the previous deploys on the same pull request are marked as inactive, but not the deploys of other pull requests.

@BBaoVanC you'll want to generate your environment name to be based on the branch. For example, see the new integration tests, which create test deployment statues per-branch: https://sourcegraph.com/github.com/bobheadxi/deployments/-/blob/.github/workflows/pipeline.yaml?L34
